/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "O-RAN.WG3.E2SM-KPM-v202v300-modified.asn1"
 * 	`asn1c -pdu=auto -fcompound-names -fno-include-deps -findirect-choice -gen-PER -gen-OER -no-gen-example`
 */

#include "MeasurementCondUEidItem-v300.h"

#include "MatchingUEidList.h"
#include "MatchingUEidPerGP.h"
asn_TYPE_member_t asn_MBR_MeasurementCondUEidItem_v300_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MeasurementCondUEidItem_v300, measType),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_MeasurementType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MeasurementCondUEidItem_v300, matchingCond),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MatchingCondList_v300,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"matchingCond"
		},
	{ ATF_POINTER, 2, offsetof(struct MeasurementCondUEidItem_v300, matchingUEidList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MatchingUEidList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"matchingUEidList"
		},
	{ ATF_POINTER, 1, offsetof(struct MeasurementCondUEidItem_v300, matchingUEidPerGP),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MatchingUEidPerGP,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"matchingUEidPerGP"
		},
};
static const int asn_MAP_MeasurementCondUEidItem_v300_oms_1[] = { 2, 3 };
static const ber_tlv_tag_t asn_DEF_MeasurementCondUEidItem_v300_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MeasurementCondUEidItem_v300_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* measType */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* matchingCond */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* matchingUEidList */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* matchingUEidPerGP */
};
asn_SEQUENCE_specifics_t asn_SPC_MeasurementCondUEidItem_v300_specs_1 = {
	sizeof(struct MeasurementCondUEidItem_v300),
	offsetof(struct MeasurementCondUEidItem_v300, _asn_ctx),
	asn_MAP_MeasurementCondUEidItem_v300_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_MeasurementCondUEidItem_v300_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MeasurementCondUEidItem_v300 = {
	"MeasurementCondUEidItem-v300",
	"MeasurementCondUEidItem-v300",
	&asn_OP_SEQUENCE,
	asn_DEF_MeasurementCondUEidItem_v300_tags_1,
	sizeof(asn_DEF_MeasurementCondUEidItem_v300_tags_1)
		/sizeof(asn_DEF_MeasurementCondUEidItem_v300_tags_1[0]), /* 1 */
	asn_DEF_MeasurementCondUEidItem_v300_tags_1,	/* Same as above */
	sizeof(asn_DEF_MeasurementCondUEidItem_v300_tags_1)
		/sizeof(asn_DEF_MeasurementCondUEidItem_v300_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_MeasurementCondUEidItem_v300_1,
	4,	/* Elements count */
	&asn_SPC_MeasurementCondUEidItem_v300_specs_1	/* Additional specs */
};

