/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "O-RAN.WG3.E2SM-KPM-v202v300-modified.asn1"
 * 	`asn1c -pdu=auto -fcompound-names -fno-include-deps -findirect-choice -gen-PER -gen-OER -no-gen-example`
 */

#ifndef	_MeasurementLabel_v300_H_
#define	_MeasurementLabel_v300_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include "PLMNIdentity.h"
#include "FiveQI.h"
#include "QosFlowIdentifier.h"
#include "QCI.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MeasurementLabel_v300__noLabel {
	MeasurementLabel_v300__noLabel_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_MeasurementLabel_v300__noLabel;
typedef enum MeasurementLabel_v300__sUM {
	MeasurementLabel_v300__sUM_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_MeasurementLabel_v300__sUM;
typedef enum MeasurementLabel_v300__preLabelOverride {
	MeasurementLabel_v300__preLabelOverride_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_MeasurementLabel_v300__preLabelOverride;
typedef enum MeasurementLabel_v300__startEndInd {
	MeasurementLabel_v300__startEndInd_start	= 0,
	MeasurementLabel_v300__startEndInd_end	= 1
	/*
	 * Enumeration is extensible
	 */
} e_MeasurementLabel_v300__startEndInd;
typedef enum MeasurementLabel_v300__min {
	MeasurementLabel_v300__min_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_MeasurementLabel_v300__min;
typedef enum MeasurementLabel_v300__max {
	MeasurementLabel_v300__max_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_MeasurementLabel_v300__max;
typedef enum MeasurementLabel_v300__avg {
	MeasurementLabel_v300__avg_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_MeasurementLabel_v300__avg;

/* Forward declarations */
struct S_NSSAI;

/* MeasurementLabel-v300 */
typedef struct MeasurementLabel_v300 {
	long	*noLabel;	/* OPTIONAL */
	PLMNIdentity_t	*plmnID;	/* OPTIONAL */
	struct S_NSSAI	*sliceID;	/* OPTIONAL */
	FiveQI_t	*fiveQI;	/* OPTIONAL */
	QosFlowIdentifier_t	*qFI;	/* OPTIONAL */
	QCI_t	*qCI;	/* OPTIONAL */
	QCI_t	*qCImax;	/* OPTIONAL */
	QCI_t	*qCImin;	/* OPTIONAL */
	long	*aRPmax;	/* OPTIONAL */
	long	*aRPmin;	/* OPTIONAL */
	long	*bitrateRange;	/* OPTIONAL */
	long	*layerMU_MIMO;	/* OPTIONAL */
	long	*sUM;	/* OPTIONAL */
	long	*distBinX;	/* OPTIONAL */
	long	*distBinY;	/* OPTIONAL */
	long	*distBinZ;	/* OPTIONAL */
	long	*preLabelOverride;	/* OPTIONAL */
	long	*startEndInd;	/* OPTIONAL */
	long	*min;	/* OPTIONAL */
	long	*max;	/* OPTIONAL */
	long	*avg;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	long	*ssbIndex;	/* OPTIONAL */
	long	*nonGoB_BFmode_Index;	/* OPTIONAL */
	long	*mIMO_mode_Index;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasurementLabel_v300_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_noLabel_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_sUM_16;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_preLabelOverride_22;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_startEndInd_25;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_min_29;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_max_32;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_avg_35;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_MeasurementLabel_v300;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasurementLabel_v300_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasurementLabel_v300_1[24];

#ifdef __cplusplus
}
#endif

#endif	/* _MeasurementLabel_v300_H_ */
#include <asn_internal.h>
